### ISSUE TITLE
Typografia

### ISSUE THREAD

**Issue by manuelbenitez** [fs4-equipo2/Replica_Lego#2]
**Titulo y subtitulo seccion Main**
![image](https://github.com/fs4-equipo2/Replica_Lego/assets/20058638/6ea7771e-3be3-4613-9b66-a9cec3464ca7)

**Titulo Navbar**
<img width="165" alt="Screen Shot 2023-11-17 at 6 01 29 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/ddfdb39b-30de-45b2-89bc-8e4542851ed4">

**Texto Prenavbar**
<img width="482" alt="Screen Shot 2023-11-17 at 6 02 04 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/41c9c8b5-1f06-48c6-b4b5-031342150466">

**Titulo y subtitulo seccion Menu**
<img width="294" alt="Screen Shot 2023-11-17 at 6 02 35 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/5d50c245-dc64-4318-9821-14ee0b55fd35">

<img width="520" alt="Screen Shot 2023-11-17 at 6 02 46 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/e3bf5d24-d0c0-4c10-a444-780eff8961cc">

**Titulo y subtitulo card de producto**

<img width="434" alt="Screen Shot 2023-11-17 at 6 07 29 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/2cd9052f-a5e1-4186-b11a-7cadb1173871">

<img width="212" alt="Screen Shot 2023-11-17 at 6 06 25 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/04693d28-2451-486f-86ce-0934ccc47c46">

<img width="232" alt="Screen Shot 2023-11-17 at 6 06 41 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/2c2e65e4-c97f-4b22-8a74-11ecdf267448">

<img width="1011" alt="Screen Shot 2023-11-17 at 6 07 15 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/fafbc26c-6dd6-4acf-8eef-baaa13432f7f">

**Titulo, subtitulo, texto Card Blog**
<img width="1060" alt="Screen Shot 2023-11-17 at 6 10 25 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/9b78c441-f6d4-4ad7-89cf-7954a27acb1b">

**Titulo Sticker**
<img width="148" alt="Screen Shot 2023-11-17 at 6 11 21 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/f6a75c73-b4f6-44d7-a886-5225fef6c86b">

**Texto Bienvenida**
<img width="1162" alt="Screen Shot 2023-11-17 at 6 12 09 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/1e5c2555-6367-4cdb-bf14-171ff9b43cc3">

**Titulos footer y links**
<img width="171" alt="Screen Shot 2023-11-17 at 6 12 34 PM" src="https://github.com/fs4-equipo2/Replica_Lego/assets/137082064/f3d92d7b-cd49-49b8-a9ca-de0a3d22b1ee">

------------------------------------------------------------------------------------------------------------------------
### NO EXISTE

**Titulo seccion **
![image](https://github.com/fs4-equipo2/Replica_Lego/assets/20058638/92ea5412-708b-4f3f-8462-6aec6659fd8a)

**Titulo card - descripcion card**
![image](https://github.com/fs4-equipo2/Replica_Lego/assets/20058638/447d4e49-cd86-4878-90bc-d093139558cd)

**Comment by Mariacortesv** [comment]
Completado
